apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkxkv2761-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkxkv2761-tenant-component
    app.kubernetes.io/part-of: loadkxkv2761-tenant-app
  name: loadkxkv2761-tenant-component
  namespace: loadkxkv2761-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadkxkv2761-tenant-component
    weight: null
status: {}
